export type Departement = {
   codeDepartement: string;
   nomDepartement: string;
   codeRegion: number;
   nomRegion: string;
};

export const departements: Departement[] = [
   {codeDepartement: '01', nomDepartement: 'Ain', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '02', nomDepartement: 'Aisne', codeRegion: 32, nomRegion: 'Hauts-de-France'},
   {codeDepartement: '03', nomDepartement: 'Allier', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {
      codeDepartement: '04',
      nomDepartement: 'Alpes-de-Haute-Provence',
      codeRegion: 93,
      nomRegion: 'Provence-Alpes-Côte d\'Azur',
   },
   {codeDepartement: '05', nomDepartement: 'Hautes-Alpes', codeRegion: 93, nomRegion: 'Provence-Alpes-Côte d\'Azur'},
   {codeDepartement: '06', nomDepartement: 'Alpes-Maritimes', codeRegion: 93, nomRegion: 'Provence-Alpes-Côte d\'Azur'},
   {codeDepartement: '07', nomDepartement: 'Ardèche', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '08', nomDepartement: 'Ardennes', codeRegion: 44, nomRegion: 'Grand Est'},
   {codeDepartement: '09', nomDepartement: 'Ariège', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '10', nomDepartement: 'Aube', codeRegion: 44, nomRegion: 'Grand Est'},
   {codeDepartement: '11', nomDepartement: 'Aude', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '12', nomDepartement: 'Aveyron', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '13', nomDepartement: 'Bouches-du-Rhône', codeRegion: 93, nomRegion: 'Provence-Alpes-Côte d\'Azur'},
   {codeDepartement: '14', nomDepartement: 'Calvados', codeRegion: 28, nomRegion: 'Normandie'},
   {codeDepartement: '15', nomDepartement: 'Cantal', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '16', nomDepartement: 'Charente', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '17', nomDepartement: 'Charente-Maritime', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '18', nomDepartement: 'Cher', codeRegion: 24, nomRegion: 'Centre-Val de Loire'},
   {codeDepartement: '19', nomDepartement: 'Corrèze', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '21', nomDepartement: 'Côte-d\'Or', codeRegion: 27, nomRegion: 'Bourgogne-Franche-Comté'},
   {codeDepartement: '22', nomDepartement: 'Côtes-d\'Armor', codeRegion: 53, nomRegion: 'Bretagne'},
   {codeDepartement: '23', nomDepartement: 'Creuse', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '24', nomDepartement: 'Dordogne', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '25', nomDepartement: 'Doubs', codeRegion: 27, nomRegion: 'Bourgogne-Franche-Comté'},
   {codeDepartement: '26', nomDepartement: 'Drôme', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '27', nomDepartement: 'Eure', codeRegion: 28, nomRegion: 'Normandie'},
   {codeDepartement: '28', nomDepartement: 'Eure-et-Loir', codeRegion: 24, nomRegion: 'Centre-Val de Loire'},
   {codeDepartement: '29', nomDepartement: 'Finistère', codeRegion: 53, nomRegion: 'Bretagne'},
   {codeDepartement: '2A', nomDepartement: 'Corse-du-Sud', codeRegion: 94, nomRegion: 'Corse'},
   {codeDepartement: '2B', nomDepartement: 'Haute-Corse', codeRegion: 94, nomRegion: 'Corse'},
   {codeDepartement: '30', nomDepartement: 'Gard', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '31', nomDepartement: 'Haute-Garonne', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '32', nomDepartement: 'Gers', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '33', nomDepartement: 'Gironde', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '34', nomDepartement: 'Hérault', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '35', nomDepartement: 'Ille-et-Vilaine', codeRegion: 53, nomRegion: 'Bretagne'},
   {codeDepartement: '36', nomDepartement: 'Indre', codeRegion: 24, nomRegion: 'Centre-Val de Loire'},
   {codeDepartement: '37', nomDepartement: 'Indre-et-Loire', codeRegion: 24, nomRegion: 'Centre-Val de Loire'},
   {codeDepartement: '38', nomDepartement: 'Isère', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '39', nomDepartement: 'Jura', codeRegion: 27, nomRegion: 'Bourgogne-Franche-Comté'},
   {codeDepartement: '40', nomDepartement: 'Landes', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '41', nomDepartement: 'Loir-et-Cher', codeRegion: 24, nomRegion: 'Centre-Val de Loire'},
   {codeDepartement: '42', nomDepartement: 'Loire', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '43', nomDepartement: 'Haute-Loire', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '44', nomDepartement: 'Loire-Atlantique', codeRegion: 52, nomRegion: 'Pays de la Loire'},
   {codeDepartement: '45', nomDepartement: 'Loiret', codeRegion: 24, nomRegion: 'Centre-Val de Loire'},
   {codeDepartement: '46', nomDepartement: 'Lot', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '47', nomDepartement: 'Lot-et-Garonne', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '48', nomDepartement: 'Lozère', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '49', nomDepartement: 'Maine-et-Loire', codeRegion: 52, nomRegion: 'Pays de la Loire'},
   {codeDepartement: '50', nomDepartement: 'Manche', codeRegion: 28, nomRegion: 'Normandie'},
   {codeDepartement: '51', nomDepartement: 'Marne', codeRegion: 44, nomRegion: 'Grand Est'},
   {codeDepartement: '52', nomDepartement: 'Haute-Marne', codeRegion: 44, nomRegion: 'Grand Est'},
   {codeDepartement: '53', nomDepartement: 'Mayenne', codeRegion: 52, nomRegion: 'Pays de la Loire'},
   {codeDepartement: '54', nomDepartement: 'Meurthe-et-Moselle', codeRegion: 44, nomRegion: 'Grand Est'},
   {codeDepartement: '55', nomDepartement: 'Meuse', codeRegion: 44, nomRegion: 'Grand Est'},
   {codeDepartement: '56', nomDepartement: 'Morbihan', codeRegion: 53, nomRegion: 'Bretagne'},
   {codeDepartement: '57', nomDepartement: 'Moselle', codeRegion: 44, nomRegion: 'Grand Est'},
   {codeDepartement: '58', nomDepartement: 'Nièvre', codeRegion: 27, nomRegion: 'Bourgogne-Franche-Comté'},
   {codeDepartement: '59', nomDepartement: 'Nord', codeRegion: 32, nomRegion: 'Hauts-de-France'},
   {codeDepartement: '60', nomDepartement: 'Oise', codeRegion: 32, nomRegion: 'Hauts-de-France'},
   {codeDepartement: '61', nomDepartement: 'Orne', codeRegion: 28, nomRegion: 'Normandie'},
   {codeDepartement: '62', nomDepartement: 'Pas-de-Calais', codeRegion: 32, nomRegion: 'Hauts-de-France'},
   {codeDepartement: '63', nomDepartement: 'Puy-de-Dôme', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '64', nomDepartement: 'Pyrénées-Atlantiques', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '65', nomDepartement: 'Hautes-Pyrénées', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '66', nomDepartement: 'Pyrénées-Orientales', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '67', nomDepartement: 'Bas-Rhin', codeRegion: 44, nomRegion: 'Grand Est'},
   {codeDepartement: '68', nomDepartement: 'Haut-Rhin', codeRegion: 44, nomRegion: 'Grand Est'},
   {codeDepartement: '69', nomDepartement: 'Rhône', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '70', nomDepartement: 'Haute-Saône', codeRegion: 27, nomRegion: 'Bourgogne-Franche-Comté'},
   {codeDepartement: '71', nomDepartement: 'Saône-et-Loire', codeRegion: 27, nomRegion: 'Bourgogne-Franche-Comté'},
   {codeDepartement: '72', nomDepartement: 'Sarthe', codeRegion: 52, nomRegion: 'Pays de la Loire'},
   {codeDepartement: '73', nomDepartement: 'Savoie', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '74', nomDepartement: 'Haute-Savoie', codeRegion: 84, nomRegion: 'Auvergne-Rhône-Alpes'},
   {codeDepartement: '75', nomDepartement: 'Paris', codeRegion: 11, nomRegion: 'Île-de-France'},
   {codeDepartement: '76', nomDepartement: 'Seine-Maritime', codeRegion: 28, nomRegion: 'Normandie'},
   {codeDepartement: '77', nomDepartement: 'Seine-et-Marne', codeRegion: 11, nomRegion: 'Île-de-France'},
   {codeDepartement: '78', nomDepartement: 'Yvelines', codeRegion: 11, nomRegion: 'Île-de-France'},
   {codeDepartement: '79', nomDepartement: 'Deux-Sèvres', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '80', nomDepartement: 'Somme', codeRegion: 32, nomRegion: 'Hauts-de-France'},
   {codeDepartement: '81', nomDepartement: 'Tarn', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '82', nomDepartement: 'Tarn-et-Garonne', codeRegion: 76, nomRegion: 'Occitanie'},
   {codeDepartement: '83', nomDepartement: 'Var', codeRegion: 93, nomRegion: 'Provence-Alpes-Côte d\'Azur'},
   {codeDepartement: '84', nomDepartement: 'Vaucluse', codeRegion: 93, nomRegion: 'Provence-Alpes-Côte d\'Azur'},
   {codeDepartement: '85', nomDepartement: 'Vendée', codeRegion: 52, nomRegion: 'Pays de la Loire'},
   {codeDepartement: '86', nomDepartement: 'Vienne', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '87', nomDepartement: 'Haute-Vienne', codeRegion: 75, nomRegion: 'Nouvelle-Aquitaine'},
   {codeDepartement: '88', nomDepartement: 'Vosges', codeRegion: 44, nomRegion: 'Grand Est'},
   {codeDepartement: '89', nomDepartement: 'Yonne', codeRegion: 27, nomRegion: 'Bourgogne-Franche-Comté'},
   {
      codeDepartement: '90',
      nomDepartement: 'Territoire de Belfort',
      codeRegion: 27,
      nomRegion: 'Bourgogne-Franche-Comté',
   },
   {codeDepartement: '91', nomDepartement: 'Essonne', codeRegion: 11, nomRegion: 'Île-de-France'},
   {codeDepartement: '92', nomDepartement: 'Hauts-de-Seine', codeRegion: 11, nomRegion: 'Île-de-France'},
   {codeDepartement: '93', nomDepartement: 'Seine-Saint-Denis', codeRegion: 11, nomRegion: 'Île-de-France'},
   {codeDepartement: '94', nomDepartement: 'Val-de-Marne', codeRegion: 11, nomRegion: 'Île-de-France'},
   {codeDepartement: '95', nomDepartement: 'Val-d\'Oise', codeRegion: 11, nomRegion: 'Île-de-France'},
   {codeDepartement: '971', nomDepartement: 'Guadeloupe', codeRegion: 1, nomRegion: 'Guadeloupe'},
   {codeDepartement: '972', nomDepartement: 'Martinique', codeRegion: 2, nomRegion: 'Martinique'},
   {codeDepartement: '973', nomDepartement: 'Guyane', codeRegion: 3, nomRegion: 'Guyane'},
   {codeDepartement: '974', nomDepartement: 'La Réunion', codeRegion: 4, nomRegion: 'La Réunion'},
   {codeDepartement: '976', nomDepartement: 'Mayotte', codeRegion: 6, nomRegion: 'Mayotte'},
]
